name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  test:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      JS_SECRET: ${{ secrets.JS_SECRET }}
      GLOBAL_VAR: "global_value"

    steps:
      - name: test secret
        run: echo "global secret is $JS_SECRET"

      - name: test global variable
        run: echo "Global variable is $GLOBAL_VAR"

      - name: test local variable
        run: echo "step-specific variable is $STEP_VAR"
        env:
          STEP_VAR: 'step_value'
